name: CI/CD para Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v3 # Actualizado a v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3 # Actualizado a v3
        with:
          node-version: '14' # Esta es la versión de Node para tu proyecto, no para la acción

      - name: Configurar variables de entorno
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "SUPABASE_URL=${SUPABASE_URL}" >> .env
          echo "SUPABASE_KEY=${SUPABASE_KEY}" >> .env

      - name: Instalar dependencias
        run: yarn install

      - name: Ejecutar pruebas
        run: yarn mocha src/app.test.js

      - name: Despliegue del Backend
        run: |
          pm2 restart app.js



        

