name: CI/CD para Backend

on:
  push:
    branches:
      - CI/CD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v3 # Actualizado a v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3 # Actualizado a v3
        with:
          node-version: '14' # Esta es la versión de Node para tu proyecto, no para la acción

      - name: Instalar dependencias
        run: yarn install # Usa 'yarn' en lugar de 'npm' para instalar dependencias

      - name: Ejecutar pruebas
        run: yarn mocha src/app.test.js # Usa 'yarn' en lugar de 'npm' para ejecutar las pruebas

      - name: Despliegue del Backend
        run: |
          pm2 restart app.js


        

