name: CI/CD para Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v3 # Actualizado a v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3 # Actualizado a v3
        with:
          node-version: '14' # Esta es la versión de Node para tu proyecto, no para la acción

      - name: Instalar dependencias
        run: yarn install # Usa 'yarn' en lugar de 'npm' para instalar dependencias

      - name: Ejecutar pruebas
        run: yarn test # Usa 'yarn' en lugar de 'npm' para ejecutar las pruebas

      - name: Despliegue del Backend
        run: |
          # Aquí colocarías los comandos para desplegar tu backend, por ejemplo:
          # - Comando para reiniciar el servidor o aplicar cambios
          # - Comando para reiniciar servicios relacionados con el backend
          # Por ejemplo, supongamos que utilizas el comando "pm2" para gestionar tu aplicación Node.js:
          pm2 restart app.js


        

